<?php

########################################################################
# Extension Manager/Repository config file for ext: "jhe_openweathermap"
#
# Auto generated by Extension Builder 2016-11-09
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'OpenWeathermap',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Jari-Herman Ernst',
	'author_email' => 'webdev@jhernst.de',
	'author_company' => '',
	'state' => 'beta',
	'version' => '11.0.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '11.5.0-11.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
