<?php

########################################################################
# Extension Manager/Repository config file for ext: "jhe_openweathermap"
#
# Auto generated by Extension Builder 2016-11-09
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Open Weather Map',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Jari-Herman Ernst',
	'author_email' => 'jhernst@network-publishing.de',
	'author_company' => 'network.publishing GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2',
			'fluid' => '6.2',
			'typo3' => '6.2.x-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
